BUILD_FILE = ../kage.js

SOURCES = license.js \
        wrap_begin.js \
        base.js \
        class.js \
        util.js \
        event_bus.js \
        antenna.js \
        component.js \
        model.js \
        view.js \
        section.js \
        wrap_end.js

all:
	echo > $(BUILD_FILE); \
	cat $(SOURCES) >> $(BUILD_FILE);
